BannedStatementsRule:
  banned:
  - STOP
  - PRINT
  - RETURN
  - ENTRY
  - DIMENSION
  - DOUBLE PRECISION
  - COMPLEX
  - GO TO
  - CONTINUE
  - FORMAT
  - COMMON
  - EQUIVALENCE
CodeBodyRule:
  max_nesting_depth: 3
ExplicitKindRule:
  allowed_type_kinds:
    INTEGER:
    - JPIM
    - JPIT
    - JPIB
    - JPIA
    - JPIS
    - JPIH
    REAL:
    - JPRB
    - JPRM
    - JPRS
    - JPRT
    - JPRH
    - JPRD
    - JPHOOK
  constant_types:
  - REAL
  declaration_types:
  - INTEGER
  - REAL
LimitSubroutineStatementsRule:
  max_num_statements: 300
MaxDummyArgsRule:
  max_num_arguments: 50
rules:
- BannedStatementsRule
- CodeBodyRule
- DrHookRule
- ExplicitKindRule
- Fortran90OperatorsRule
- ImplicitNoneRule
- LimitSubroutineStatementsRule
- MaxDummyArgsRule
- ModuleNamingRule
- MplCdstringRule
